New json ld contexts
ONSdigital/explore-local-statistics-data pull request #197
Opened 2024-10-03 11:50 UTC by GregoryJPavier

2024-10-04 10:33 UTC, sazzadur-ons commented on business-expenditure-on-research-and-development/business-expenditure-on-research-and-development-context.json
> +                "E12"
E12 is region. If only 'E12' region is added to "spatial_resolution", then "Nation" is skipped.
So I think "E92", "N92", "S92", "W92" should be added also as these represent "Nation".

2024-10-04 10:39 UTC, sazzadur-ons commented on business-demography/business-demography-context.json
> +            "spatial_resolution": [
"Country" was added to "spatial_coverage".
If only regions are added to "spatial_resolution", then "Nation" is skipped. 
So I think "E92", "N92", "S92", "W92" should be added to "spatial_resolution" also as these represent "Nation".

2024-10-07 15:27 UTC, sazzadur-ons requested changes

2024-10-07 15:27 UTC, sazzadur-ons commented on supermarkets/supermarkets-context.json
> +            "spatial_resolution": [
"E06",
                "E07",
                "E08",
                "E09",
                "E10",
                "E12",
                "E47",
                "E92",
                "N09",
                "N92",
                "S12",
                "S92",
                "W06",
                "W92"

2024-10-07 15:27 UTC, sazzadur-ons commented on supermarkets/supermarkets-context.json
> +            "temporal_coverage": {
It is Month.

"temporal_coverage": {
                "@type": "dcterms:PeriodOfTime",
                "start": "2023-08-01T00:00:00+00:00",
                "end": "2023-08-31T00:00:00+00:00"
            },
            "temporal_resolution": [
                "P1M"
            ],

2024-10-07 15:27 UTC, sazzadur-ons commented on total-value-of-uk-exports/total-value-of-uk-exports-context.json
> +                "columns": [
"columns": [
                    {
                        "name": "AREACD",
                        "titles": "Area Code",
                        "datatype": "string"
                    },
                    {
                        "name": "AREANM",
                        "titles": "Area Name",
                        "datatype": "string"
                    },
                    {
                        "name": "Geography",
                        "titles": "Geography",
                        "datatype": "string"
                    },
                    {
                        "name": "Variable Name",
                        "titles": "Variable Name",
                        "datatype": "string"
                    },
                    {
                        "name": "Indicator",
                        "titles": "Indicator",
                        "datatype": "string"
                    },
                    {
                        "name": "Mission",
                        "titles": "Mission",
                        "datatype": "string"
                    },
                    {
                        "name": "Category",
                        "titles": "Category",
                        "datatype": "string"
                    },
                    {
                        "name": "Period",
                        "titles": "Period",
                        "datatype": "string"
                    },
                    {
                        "name": "Observation",
                        "titles": "Observation",
                        "datatype": "decimal"
                    },
                    {
                        "name": "Measure",
                        "titles": "Measure",
                        "datatype": "string"
                    },
                    {
                        "name": "Unit",
                        "titles": "Unit",
                        "datatype": "string"
                    },
                    {
                        "name": "Lower Confidence Interval (95%)",
                        "titles": "Lower Confidence Interval (95%)",
                        "datatype": "decimal"
                    },
                    {
                        "name": "Upper Confidence Interval (95%)",
                        "titles": "Upper Confidence Interval (95%)",
                        "datatype": "decimal"
                    },
                    {
                        "name": "Observation Status",
                        "titles": "Observation Status",
                        "datatype": "string"
                    },
                    {
                        "name": "Polarity",
                        "titles": "Polarity",
                        "datatype": "string"
                    },
                    {
                        "name": "Notes",
                        "titles": "Notes",
                        "datatype": "string"
                    }
                ]

2024-10-07 15:27 UTC, sazzadur-ons commented on total-value-of-uk-exports/total-value-of-uk-exports-context.json
> +            "spatial_resolution": [
"E13", 
                "E47", 
                "E92", 
                "N34", 
                "TLC", 
                "TLD", 
                "TLE", 
                "TLF", 
                "TLG",
                "TLH", 
                "TLI", 
                "TLJ", 
                "TLK", 
                "TLL", 
                "TLM", 
                "TLN", 
                "W42"

2024-10-07 15:27 UTC, sazzadur-ons commented on uk-small-area-gross-value-added-estimates/2011-england-and-wales-super-output-areas-lower-layer-context.json
> +                "columns": [
"columns": [
                    {
                        "name": "AREANM",
                        "titles": "Area Name",
                        "datatype": "string"
                    },
                    {
                        "name": "AREACD",
                        "titles": "Area Code",
                        "datatype": "string"
                    },
                    {
                        "name": "Period",
                        "titles": "Period",
                        "datatype": "string"
                    },
                    {
                        "name": "Observation",
                        "titles": "Observation",
                        "datatype": "decimal"
                    }
                ]

2024-10-07 15:27 UTC, sazzadur-ons commented on uk-small-area-gross-value-added-estimates/2011-northern-ireland-super-output-areas-context.json
> +                "columns": [
"columns": [
                    {
                        "name": "AREANM",
                        "titles": "Area Name",
                        "datatype": "string"
                    },
                    {
                        "name": "AREACD",
                        "titles": "Area Code",
                        "datatype": "string"
                    },
                    {
                        "name": "Period",
                        "titles": "Period",
                        "datatype": "string"
                    },
                    {
                        "name": "Observation",
                        "titles": "Observation",
                        "datatype": "decimal"
                    }
                ]

2024-10-07 15:27 UTC, sazzadur-ons commented on uk-small-area-gross-value-added-estimates/2011-scottish-data-zones-context.json
> +                "columns": [
"columns": [
                    {
                        "name": "AREANM",
                        "titles": "Area Name",
                        "datatype": "string"
                    },
                    {
                        "name": "AREACD",
                        "titles": "Area Code",
                        "datatype": "string"
                    },
                    {
                        "name": "Period",
                        "titles": "Period",
                        "datatype": "string"
                    },
                    {
                        "name": "Observation",
                        "titles": "Observation",
                        "datatype": "decimal"
                    }
                ]

2024-10-11 08:40 UTC, GregoryJPavier commented on museums/museums-context.json
> +                "end": "2021-09-30T00:00:00+00:00"
The description uses the term 'as at 30 September 2021' which would mean that data applies to that specific time only. Might have to ask ESS if that's actually what they mean here. I've represented what they've said in the description here but the resolution is then wrong, so need to figure out the correct format for that.

2024-10-11 08:43 UTC, GregoryJPavier commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england-context.json
> +                "end": "2023-01-13T00:00:00+00:00"
Description states 'as of' which means the data is as it was on that date, as such it shouldn't go beyond that date. Again, the temporal resolution I think needs to be changed here.

2024-10-11 08:45 UTC, GregoryJPavier commented on premises-below-30/premises-below-30-context.json
> +                "end": "2024-01-01T00:00:00+00:00"
Another 'as of' case. The data, nor the description, make it explicit whether it's as of the beginning or end of January, so I've just used the beginning. Like the previous examples, resolution needs another look.

2024-10-11 09:03 UTC, GregoryJPavier commented on supermarkets/supermarkets-context.json
> +            "temporal_coverage": {
Another case of 'as at'. So may need to confirm with ESS if that means the start or end of August. Again, temporal resolution needs a look.

2024-10-11 15:05 UTC, GregoryJPavier commented on sports-facilities/sports-facilites-context.json
> +                "P1Y"
Since we use ISO-8061 codes for the duration it makes representing a gregorian instant difficult. I guess we go with your suggestion of just using 'P' for now?

2024-10-11 15:06 UTC, GregoryJPavier commented on museums/museums-context.json
> +                "end": "2021-09-30T00:00:00+00:00"
Resorted to using 'P' as it's a gregorian instant

2024-10-11 15:08 UTC, GregoryJPavier commented on population-under-devolution-deal-in-england/population-under-devolution-deal-in-england-context.json
> +                "end": "2023-01-13T00:00:00+00:00"
Gregorian instant, so using 'P'

2024-10-11 15:09 UTC, GregoryJPavier commented on premises-below-30/premises-below-30-context.json
> +                "end": "2024-01-01T00:00:00+00:00"
Gregorian instant, so using 'P' for temporal resolution.

2024-10-11 15:14 UTC, GregoryJPavier commented on schools-and-nursery-schools-rated-good-or-outstanding/schools-and-nursery-schools-rated-good-or-outstanding-context.json
> +                "start": "2024-04-30T00:00:00+00:00",
Changed temporal resolution to 'P'

2024-10-15 13:32 UTC, merged