Created claimant count json ld context file
ONSdigital/explore-local-statistics-data pull request #208
Opened 2024-11-05 14:18 UTC by GregoryJPavier

2024-11-05 16:41 UTC, sazzadur-ons requested changes

2024-11-05 16:41 UTC, sazzadur-ons commented on claimant-count/claimant-count-context.json
> +    "@id": "https://ons.gov.uk/datasets/claimant-count/editions/2024-Q4/versions/2",
It is new dataset. Should it not be "versions/1" instead of "versions/2"?

2024-11-06 11:21 UTC, GregoryJPavier commented on claimant-count/claimant-count-context.json
> +    "@id": "https://ons.gov.uk/datasets/claimant-count/editions/2024-Q4/versions/2",
I've put version 2 since it's been modified at least once:
- "issued": "2024-10-31T13:47",
- "modified": "2024-11-04T13:47",

2024-11-07 11:13 UTC, sazzadur-ons commented
You can merge

2024-11-07 11:23 UTC, sazzadur-ons approved these changes

2024-11-07 14:14 UTC, merged